# Generated by Django 5.2.7 on 2025-12-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordcode',
            name='code',
            field=models.IntegerField(),
        ),
    ]
