# Generated by Django 5.2.7 on 2026-03-26 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_resetpasswordcode_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='government_document',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='is_verified',
        ),
    ]
