# Generated by Django 5.2.7 on 2026-03-26 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_supervisor_government_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='phone',
        ),
    ]
