# Generated by Django 5.2.7 on 2026-03-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_alter_issue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('lighting', 'إنارة'), ('pothole', 'نقرة'), ('speed_bump', 'مطب'), ('traffic_sign', 'لافتة مرورية'), ('road_damage', 'تلف طريق'), ('other', 'أخرى')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='issue',
            name='type',
            field=models.CharField(default='unspecified', max_length=100),
        ),
    ]
