# Generated by Django 5.2.7 on 2026-03-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_issue_category_issue_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='type',
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
