# Generated by Django 5.2.7 on 2026-06-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_devicetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Pending', 'قيد الانتظار'), ('In Progress', 'جاري العمل'), ('Resolved', 'تم الحل'), ('Rejected', 'تم الرفض')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('issue_update', 'تحديث بلاغ'), ('city_alert', 'تنبيه في المدينة')], max_length=20),
        ),
    ]
