# Generated by Django 5.2.7 on 2026-06-22 14:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_alter_issue_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_issues', to=settings.AUTH_USER_MODEL),
        ),
    ]
