# Generated by Django 5.2.7 on 2026-06-22 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_issue_dislikes_issue_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='likes',
        ),
    ]
