# Generated by Django 5.2.7 on 2026-06-24 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_remove_issue_dislikes_remove_issue_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='tasdeeqs',
            field=models.ManyToManyField(blank=True, related_name='tasdeeq_issues', to=settings.AUTH_USER_MODEL),
        ),
    ]
